In [1]:
pip install gmaps

Requirement already satisfied: gmaps in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (0.9.0)
Requirement already satisfied: traitlets>=4.3.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (5.0.5)
Requirement already satisfied: ipywidgets>=7.0.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (7.6.3)
Requirement already satisfied: ipython>=5.3.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (7.22.0)
Requirement already satisfied: six in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (1.15.0)
Requirement already satisfied: geojson>=2.0.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from gmaps) (2.5.0)
Requirement already satisfied: pexpect>4.3 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (4.8.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (3.0.17)
Requirement already satisfied: decorator in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (5.0.6)
Requirement already satisfied: backcall in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.2.0)
Requirement already satisfied: pygments in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (2.8.1)
Requirement already satisfied: appnope in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.1.2)
Requirement already satisfied: jedi>=0.16 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.17.2)
Requirement already satisfied: pickleshare in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipython>=5.3.0->gmaps) (52.0.0.post20210125)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->gmaps) (1.0.0)
Requirement already satisfied: nbformat>=4.2.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->gmaps) (5.1.3)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->gmaps) (5.3.4)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: tornado>=4.2 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1)
Requirement already satisfied: jupyter-client in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.12)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from jedi>=0.16->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: jupyter-core in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.7.1)
Requirement already satisfied: ipython-genutils in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (20.3.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from pexpect>4.3->ipython>=5.3.0->gmaps) (0.7.0)
Requirement already satisfied: wcwidth in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.3.0)
Requirement already satisfied: prometheus-client in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.10.1)
Requirement already satisfied: terminado>=0.8.3 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.9.4)
Requirement already satisfied: jinja2 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.3)
Requirement already satisfied: Send2Trash>=1.5.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: argon2-cffi in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.1.0)
Requirement already satisfied: pyzmq>=17 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.0.0)
Requirement already satisfied: nbconvert in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.0.7)
Requirement already satisfied: python-dateutil>=2.1 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: cffi>=1.0.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.14.5)
Requirement already satisfied: pycparser in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.3)
Requirement already satisfied: defusedxml in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.1.2)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: bleach in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.3.0)
Requirement already satisfied: testpath in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.3)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)

Requirement already satisfied: async-generator in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.10)
Requirement already satisfied: nest-asyncio in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.1)
Requirement already satisfied: webencodings in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Requirement already satisfied: packaging in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/josephbassil/opt/anaconda3/lib/python3.8/site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.4.7)
Note: you may need to restart the kernel to use updated packages.

In [2]:
conda install -c conda-forge gmaps

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [3]:
import gmaps

In [4]:
import pandas as pd
import requests
from config import g_key

In [5]:
city_data_df=pd.read_csv('weather_data/cities.csv')
city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Sibolga,ID,2021-10-13 16:05:29,1.7427,98.7792,77.22,88,100,1.95
1,1,Kwinana,AU,2021-10-13 16:00:36,-32.2500,115.7667,58.14,76,0,9.04
2,2,Atuona,PF,2021-10-13 16:05:30,-9.8000,-139.0333,76.59,79,43,17.74
3,3,Ilek,RU,2021-10-13 16:05:31,51.5271,53.3831,50.14,38,100,8.59
4,4,Lakhdenpokhya,RU,2021-10-13 16:05:31,61.5198,30.1992,39.81,84,70,4.09
...,...,...,...,...,...,...,...,...,...,...
561,561,Asfi,MA,2021-10-13 16:10:52,32.2994,-9.2372,70.61,75,11,13.71
562,562,Skibotn,NO,2021-10-13 16:10:53,69.3913,20.2679,37.40,92,94,3.98
563,563,Mujiayingzi,CN,2021-10-13 16:10:54,42.1167,118.7833,52.77,74,100,6.62
564,564,Srednekolymsk,RU,2021-10-13 16:10:55,67.4500,153.6833,13.01,95,100,5.01
565,565,Hirna,ET,2021-10-13 16:10:55,9.2167,41.1000,68.54,49,100,3.02

In [6]:
city_data_df[city_data_df['Max Temp']<0]

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
156,156,Cherskiy,RU,2021-10-13 16:06:57,68.7500,161.3000,-7.38,93,67,1.99
388,388,Bilibino,RU,2021-10-13 16:09:10,68.0546,166.4372,-5.73,94,24,5.14

In [7]:
#Data point for gmaps should be either integer or floating points
#Let's check our columns
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [8]:
#Let's configure our gmaps to use our API key:
#We only need to configure our gmaps one time
gmaps.configure(api_key='AIzaSyD5cNQkfmgnUMvyR-i3p-E-YinjzaLm5RM')

In [9]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [10]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
#Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of percent Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
#Ask the customer to add a minimum and maximum temperature value
min_temp=float(input('What is the minimum temperature you would like for your trip?'))
max_temp=float(input('What is the maximum temperature you would like for your trip?'))

What is the minimum temperature you would like for your trip?75
What is the maximum temperature you would like for your trip?90

In [15]:
preferred_cities_df=city_data_df.loc[(city_data_df['Max Temp']<=max_temp)&\
                                    (city_data_df['Max Temp']>=min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Sibolga,ID,2021-10-13 16:05:29,1.7427,98.7792,77.22,88,100,1.95
2,2,Atuona,PF,2021-10-13 16:05:30,-9.8000,-139.0333,76.59,79,43,17.74
9,9,Labuhan,ID,2021-10-13 16:05:35,-6.8844,112.2051,80.06,71,73,8.52
11,11,Matara,LK,2021-10-13 16:05:36,5.9485,80.5353,79.86,85,71,11.16
20,20,Salamiyah,SY,2021-10-13 16:05:40,35.0113,37.0532,76.03,25,68,2.77
29,29,Owando,CG,2021-10-13 16:05:45,-0.4819,15.8999,83.55,67,96,2.95
34,34,Barretos,BR,2021-10-13 16:05:48,-20.5572,-48.5678,88.99,34,1,5.57
37,37,Avarua,CK,2021-10-13 16:05:49,-21.2078,-159.7750,75.25,73,20,10.36
40,40,Port Keats,AU,2021-10-13 16:05:51,-14.2500,129.5500,80.83,78,42,6.17
42,42,Victoria,HK,2021-10-13 16:04:38,22.2855,114.1577,82.38,90,69,11.01

In [16]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       0
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [17]:
preferred_cities_df.columns

Index(['City_ID', 'City', 'Country', 'Date', 'Lat', 'Lng', 'Max Temp',
       'Humidity', 'Cloudiness', 'Wind Speed'],
      dtype='object')

In [18]:
#Let's make a copy of the preferred_city_df with: City, Country, Max Temp, Lat, Lng, and hotel Name
hotel_df=preferred_cities_df[['City','Country','Max Temp','Lat','Lng']].copy()
hotel_df['Hotel Name']=''
hotel_df.head(10)

          City Country  Max Temp      Lat       Lng Hotel Name
0      Sibolga      ID     77.22   1.7427   98.7792
2       Atuona      PF     76.59  -9.8000 -139.0333
9      Labuhan      ID     80.06  -6.8844  112.2051
11      Matara      LK     79.86   5.9485   80.5353
20   Salamiyah      SY     76.03  35.0113   37.0532
29      Owando      CG     83.55  -0.4819   15.8999
34    Barretos      BR     88.99 -20.5572  -48.5678
37      Avarua      CK     75.25 -21.2078 -159.7750
40  Port Keats      AU     80.83 -14.2500  129.5500
42    Victoria      HK     82.38  22.2855  114.1577

In [21]:
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [22]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Sibolga,ID,77.22,1.7427,98.7792,Hotel Syariah CN Darussalam
2,Atuona,PF,76.59,-9.8000,-139.0333,Villa Enata
9,Labuhan,ID,80.06,-6.8844,112.2051,PT PPI Lamongan Tambak C
11,Matara,LK,79.86,5.9485,80.5353,Amaloh Boutique Resort
20,Salamiyah,SY,76.03,35.0113,37.0532,Gondolas Forum grandchildren and grandparents
29,Owando,CG,83.55,-0.4819,15.8999,Exaunel Hotel Owando
34,Barretos,BR,88.99,-20.5572,-48.5678,Dan Inn Barretos
37,Avarua,CK,75.25,-21.2078,-159.7750,Paradise Inn
40,Port Keats,AU,80.83,-14.2500,129.5500,TDC Village (Hundred Man Camp)
42,Victoria,HK,82.38,22.2855,114.1577,Mini Hotel Central

In [28]:
#let's create a maximum temp heatmap for the hotel df
locations=hotel_df[['Lat','Lng']]
max_temp=hotel_df['Max Temp']

fig=gmaps.figure(center=(30.0,31.0),zoom_level=1.5)

heat_layer=gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
                              max_intensity=300,point_radius=4)
marker_layer=gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [27]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

hotel_info=[info_box_template.format(**row) for index,row in hotel_df.iterrows()]