## Deliverable 3. Create a Travel Itinerary Map.

In [72]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [6]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Rikitea,PF,75.49,few clouds,-23.1203,-134.9692,People ThankYou
1,4,Victoria,HK,83.97,broken clouds,22.2855,114.1577,Mini Hotel Central
2,5,Hithadhoo,MV,81.59,overcast clouds,-0.6000,73.0833,Scoop Guest House
3,13,Pochutla,MX,76.82,overcast clouds,15.7432,-96.4661,Hotel Posada San Jose
4,21,Butaritari,KI,83.62,overcast clouds,3.0707,172.7902,Isles Sunset Lodge
...,...,...,...,...,...,...,...,...
176,729,Pasir Gudang,MY,87.91,broken clouds,1.4584,103.8805,Swan Garden Hotel
177,731,Sadiqabad,PK,82.54,clear sky,28.3062,70.1307,MIDWAY HOTEL & RESTAURANT
178,738,Oum Hadjer,TD,80.82,few clouds,13.2954,19.6966,NaN
179,743,Soyo,AO,75.52,overcast clouds,-6.1349,12.3689,Hotel Mpampa
180,746,Nishihara,JP,76.66,broken clouds,26.1842,127.7558,Minshuku Agaihama

In [10]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City']=='Jardim De Piranhas']
vacation_end = vacation_df.loc[vacation_df['City']=='Jardim De Piranhas']
vacation_stop1 = vacation_df.loc[vacation_df['City']=='Upanema']
vacation_stop2 = vacation_df.loc[vacation_df['City']=='Touros'] 
vacation_stop3 = vacation_df.loc[vacation_df['City']=='Cabedelo']

In [71]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start_lat = vacation_start.to_numpy()[0][5]
start_lng = vacation_start.to_numpy()[0][6]
start=(start_lat,start_lng)


end_lat =vacation_end.to_numpy()[0][5]
end_lng=vacation_end.to_numpy()[0][6]
end=(end_lat,end_lng)

stop1_lat = vacation_stop1.to_numpy()[0][5]
stop1_lng=vacation_stop1.to_numpy()[0][6]
stop1=(stop1_lat,stop1_lng)

stop2_lat = vacation_stop2.to_numpy()[0][5]
stop2_lng=vacation_stop2.to_numpy()[0][6]
stop2=(stop2_lat,stop2_lng)


stop3_lat = vacation_stop3.to_numpy()[0][5]
stop3_lng=vacation_stop3.to_numpy()[0][6]
stop3=(stop3_lat,stop3_lng)

In [84]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig=gmaps.figure()
start_to_end=gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3],
                                   travel_mode="DRIVING")
fig.add_layer(start_to_end)
fig

Figure(layout=FigureLayout(height='420px'))

In [85]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_end,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,348,Jardim De Piranhas,BR,79.25,scattered clouds,-6.3786,-37.3519,Área de Lazer Olho D'água
1,348,Jardim De Piranhas,BR,79.25,scattered clouds,-6.3786,-37.3519,Área de Lazer Olho D'água
2,309,Upanema,BR,78.39,few clouds,-5.6419,-37.2578,Hotel Central de Upanema
3,532,Touros,BR,78.40,scattered clouds,-5.1989,-35.4608,INN NEW HORIZON
4,648,Cabedelo,BR,77.68,broken clouds,-6.9811,-34.8339,Hotel Pigalle

In [90]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [91]:
# 11a. Add a marker layer for each city to the map. 
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))